### ISSUE TITLE
Will often return portuguese subtitles when asked for English

### ISSUE THREAD

**Issue by Gabriel-p** [Diaoul/subliminal#1002]
This has happened to me numerous times for different files. It always displays the same warning:

    Some providers have been discarded due to unexpected errors: legendastv, opensubtitles

**Comment by queeup** [comment]
Probably you are not using your credentials for that sites.
```shell
subliminal --opensubtitles YOUR_USERNAME YOUR_PASSWORD download -p opensubtitles /your/movie/directory/
```

**Comment by ratoaq2** [comment]
It's very hard to help you once you don't provide the command line you're using and also no debug logs.

**Comment by Gabriel-p** [comment]
The command is the standard one:

    subliminal download -l en name_of_movie

I didn't even know this tool kept a log. Where can I find it so I paste it here?

**Comment by safeaim** [comment]
I'm getting the same issue.

It appears to be that shooter.cn is returning the spanish or portuguese subtitles: 
`subliminal --debug download  -l eng -f -v "The.Good.Place.S03E04.HDTV.x264-SVA.mkv"

DEBUG:subliminal.cli:Collecting path The.Good.Place.S03E04.HDTV.x264-SVA.mkv
INFO:subliminal.core:Scanning video 'The.Good.Place.S03E04.HDTV.x264-SVA.mkv' in ''
DEBUG:subliminal.core:Size is 136706348
INFO:subliminal.core:Refining video with hash
DEBUG:subliminal.refiners.hash:Computing hashes for 'The.Good.Place.S03E04.HDTV.x264-SVA.mkv'
DEBUG:subliminal.refiners.hash:Computed hashes {'opensubtitles': '155b70b20a68ab17', 'shooter': '399e8f7ec8ebac9132d8b09a68e1801f;4b0f2bca886da9bff795b1f8cfc9cd88;51e70e7c806398cc268f5d11f7f30fee;b89ca3a97db1d5b1fb0b5e9535c71de7', 'thesubdb': 'f55ef7132b4e3c41fc6708559004cc9a'}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found video_codec H.264
DEBUG:subliminal.refiners.metadata:Found audio_codec AAC
DEBUG:subliminal.refiners.metadata:MKV has no subtitle track
INFO:subliminal.core:Refining video with tvdb
INFO:subliminal.refiners.tvdb:Searching series 'The Good Place'
DEBUG:subliminal.refiners.tvdb:Found 3 results
DEBUG:subliminal.refiners.tvdb:Found exact match on series 'The Good Place'
DEBUG:subliminal.refiners.tvdb:Found series {'id': 311711, 'seriesId': '199859', 'seriesName': 'The Good Place', 'aliases': [], 'season': '4', 'poster': 'posters/311711-3.jpg', 'banner': 'graphical/311711-g.jpg', 'fanart': 'fanart/original/311711-10.jpg', 'status': 'Ended', 'firstAired': '2016-09-19', 'network': 'NBC', 'networkId': '148', 'runtime': '25', 'language': 'en', 'genre': ['Comedy', 'Fantasy', 'Romance'], 'overview': "Eleanor Shellstrop is an ordinary woman who, through an extraordinary string of events, enters the afterlife where she comes to realize that she hasn't been a very good person. With the help of her wise afterlife mentor, she's determined to shed her old way of living and discover the awesome (or at least the pretty good) person within.", 'lastUpdated': 1594719313, 'airsDayOfWeek': 'Thursday', 'airsTime': '8:30 PM', 'rating': 'TV-14', 'imdbId': 'tt4955642', 'zap2itId': 'SH02349044', 'added': '2016-05-15 11:55:18', 'addedBy': 171, 'siteRating': 8.7, 'siteRatingCount': 693, 'slug': 'the-good-place'}
INFO:subliminal.refiners.tvdb:Getting series episode 3x4
DEBUG:subliminal.refiners.tvdb:Found episode {'id': 6914549, 'airedSeason': 3, 'airedSeasonID': 766339, 'airedEpisodeNumber': 4, 'episodeName': 'Jeremy Bearimy', 'firstAired': '2018-10-25', 'guestStars': [], 'directors': ["Trent O'Donnell"], 'writers': ['Megan Amram'], 'overview': 'The group explores the three main branches of ethical thought.', 'language': {'episodeName': 'en', 'overview': 'en'}, 'productionCode': '', 'showUrl': '', 'lastUpdated': 1580298640, 'dvdDiscid': '', 'dvdSeason': 3, 'dvdEpisodeNumber': 5, 'dvdChapter': None, 'absoluteNumber': 31, 'filename': 'episodes/311711/6914549.jpg', 'seriesId': 311711, 'lastUpdatedBy': 171304, 'airsAfterSeason': None, 'airsBeforeSeason': None, 'airsBeforeEpisode': None, 'imdbId': 'tt8601206', 'contentRating': 'TV-14', 'thumbAuthor': 1, 'thumbAdded': '2019-11-13 09:35:49', 'thumbWidth': '640', 'thumbHeight': '360', 'siteRating': 0, 'siteRatingCount': 0, 'isMovie': 0}
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No apikey. Skipping omdb refiner.
1 video collected / 0 video ignored / 0 error
INFO:subliminal.core:Skipping provider 'argenteam': no language to search for
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider legendastv
ERROR:subliminal.utils:Unexpected error. Provider legendastv
Traceback (most recent call last):
  File "/Users/myuser/subliminal/lib/python3.7/site-packages/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/Users/myuser/subliminal/lib/python3.7/site-packages/subliminal/core.py", line 66, in __getitem__
    provider = provider_manager[name].plugin(**self.provider_configs.get(name, {}))
  File "/Users/myuser/subliminal/lib/python3.7/site-packages/subliminal/providers/legendastv.py", line 164, in __init__
    rarfile.custom_check([rarfile.UNRAR_TOOL], True)
AttributeError: module 'rarfile' has no attribute 'custom_check'
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [en]>}
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages {<Language [en]>}
INFO:subliminal.core:Listing subtitles with provider 'shooter' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.core:Initializing provider podnapisi
INFO:subliminal.core:Listing subtitles with provider 'thesubdb' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider shooter
INFO:subliminal.providers.opensubtitles:Logging in
INFO:subliminal.core:Listing subtitles with provider 'tvsubtitles' and languages {<Language [en]>}
INFO:subliminal.providers.podnapisi:Searching subtitles {'sXML': 1, 'sL': 'en', 'sK': 'The Good Place', 'sTS': 3, 'sTE': 4, 'sY': 2016}
INFO:subliminal.core:Discarding provider legendastv
INFO:subliminal.core:Initializing provider thesubdb
INFO:subliminal.core:Initializing provider tvsubtitles
INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': 'f55ef7132b4e3c41fc6708559004cc9a'}
DEBUG:subliminal.providers.shooter:Searching subtitles {'filehash': '399e8f7ec8ebac9132d8b09a68e1801f;4b0f2bca886da9bff795b1f8cfc9cd88;51e70e7c806398cc268f5d11f7f30fee;b89ca3a97db1d5b1fb0b5e9535c71de7', 'pathinfo': '/Users/myuser/Downloads/The Good Place Season 3/The.Good.Place.S03E04.HDTV.x264-SVA.mkv', 'format': 'json', 'lang': 'eng'}
INFO:subliminal.providers.tvsubtitles:Getting the page for episode 71621
ERROR:subliminal.utils:Unexpected error. Provider opensubtitles
Traceback (most recent call last):
  File "/Users/myuser/subliminal/lib/python3.7/site-packages/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/Users/myuser/subliminal/lib/python3.7/site-packages/subliminal/core.py", line 67, in __getitem__
    provider.initialize()
  File "/Users/myuser/subliminal/lib/python3.7/site-packages/subliminal/providers/opensubtitles.py", line 129, in initialize
    response = checked(self.server.LogIn(self.username, self.password, 'eng', self.user_agent))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1279, in send_request
    self.send_content(connection, request_body)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xmlrpc/client.py", line 1309, in send_content
    connection.endheaders(request_body)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.opensubtitles.org'. (_ssl.c:1056)
INFO:subliminal.core:Discarding provider opensubtitles
DEBUG:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle 'f55ef7132b4e3c41fc6708559004cc9a-en' [en]>
DEBUG:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle 'f55ef7132b4e3c41fc6708559004cc9a-pt-BR' [pt-BR]>
DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'h8dF' [en]>
DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'g8dF' [en]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '338043' [en]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '337924' [es]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '337974' [el]>
INFO:subliminal.score:Computing score of <PodnapisiSubtitle 'h8dF' [en]> for video <Episode [The Good Place2016 s03e04]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 809, 'series': 405, 'year': 135, 'country': 135, 'season': 45, 'episode': 45, 'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'year', 'season', 'release_group', 'episode', 'source', 'video_codec', 'country', 'series'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 790 with final matches {'year', 'season', 'release_group', 'episode', 'source', 'video_codec', 'country', 'series', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <PodnapisiSubtitle 'g8dF' [en]> for video <Episode [The Good Place2016 s03e04]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 809, 'series': 405, 'year': 135, 'country': 135, 'season': 45, 'episode': 45, 'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'year', 'season', 'release_group', 'episode', 'source', 'country', 'series'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 788 with final matches {'year', 'season', 'release_group', 'episode', 'source', 'country', 'series', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <ShooterSubtitle 'https://www.shooter.cn/api/subapi.php?fetch=MTU5NTk1NTk5NnxsU2xVanJJcFF2YnlKV25ROWlITl9Kc1FkVWk5Vndtck9CejhjZE95SGlVV1JHbVpOVElYeExTR05sMGQxSTI4ZHFvY0JEcktiNzdmaGpBRFZYV0JELVpBSDY4TnpCZzBmaE1mMVIzUktYODNRTzdRQzVvMGVwRUFXelRVYXRBYVpaTDVwOW9QSzlKQURPYmZQRG51a3ZZPXzC_gwXdhO_V83bmLTGLzXutvklLEUje-MdU_K6e6rh0A==&nonce=%0A%B8%18%CA%8D%A3%8CD%60%A9%9E%60x%26%B9V' [en]> for video <Episode [The Good Place2016 s03e04]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 809, 'series': 405, 'year': 135, 'country': 135, 'season': 45, 'episode': 45, 'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'hash'}
DEBUG:subliminal.score:Keeping only hash match
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 810 with final matches {'hash', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <TheSubDBSubtitle 'f55ef7132b4e3c41fc6708559004cc9a-en' [en]> for video <Episode [The Good Place2016 s03e04]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 809, 'series': 405, 'year': 135, 'country': 135, 'season': 45, 'episode': 45, 'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'hash'}
DEBUG:subliminal.score:Keeping only hash match
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 810 with final matches {'hash', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <TVsubtitlesSubtitle '338043' [en]> for video <Episode [The Good Place2016 s03e04]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 809, 'series': 405, 'year': 135, 'country': 135, 'season': 45, 'episode': 45, 'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'year', 'season', 'release_group', 'episode', 'source', 'country', 'series'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 788 with final matches {'year', 'season', 'release_group', 'episode', 'source', 'country', 'series', 'hearing_impaired'}
INFO:subliminal.core:Downloading subtitle <ShooterSubtitle 'https://www.shooter.cn/api/subapi.php?fetch=MTU5NTk1NTk5NnxsU2xVanJJcFF2YnlKV25ROWlITl9Kc1FkVWk5Vndtck9CejhjZE95SGlVV1JHbVpOVElYeExTR05sMGQxSTI4ZHFvY0JEcktiNzdmaGpBRFZYV0JELVpBSDY4TnpCZzBmaE1mMVIzUktYODNRTzdRQzVvMGVwRUFXelRVYXRBYVpaTDVwOW9QSzlKQURPYmZQRG51a3ZZPXzC_gwXdhO_V83bmLTGLzXutvklLEUje-MdU_K6e6rh0A==&nonce=%0A%B8%18%CA%8D%A3%8CD%60%A9%9E%60x%26%B9V' [en]>
INFO:subliminal.providers.shooter:Downloading subtitle <ShooterSubtitle 'https://www.shooter.cn/api/subapi.php?fetch=MTU5NTk1NTk5NnxsU2xVanJJcFF2YnlKV25ROWlITl9Kc1FkVWk5Vndtck9CejhjZE95SGlVV1JHbVpOVElYeExTR05sMGQxSTI4ZHFvY0JEcktiNzdmaGpBRFZYV0JELVpBSDY4TnpCZzBmaE1mMVIzUktYODNRTzdRQzVvMGVwRUFXelRVYXRBYVpaTDVwOW9QSzlKQURPYmZQRG51a3ZZPXzC_gwXdhO_V83bmLTGLzXutvklLEUje-MdU_K6e6rh0A==&nonce=%0A%B8%18%CA%8D%A3%8CD%60%A9%9E%60x%26%B9V' [en]>
INFO:subliminal.subtitle:Guessing encoding for language en
DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'latin-1']
INFO:subliminal.subtitle:Guessed encoding latin-1
INFO:subliminal.subtitle:Guessing encoding for language en
DEBUG:subliminal.subtitle:Trying encodings ['utf-8', 'latin-1']
INFO:subliminal.subtitle:Guessed encoding latin-1
DEBUG:subliminal.core:All languages downloaded
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: legendastv, opensubtitles
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider podnapisi
INFO:subliminal.core:Terminating provider shooter
INFO:subliminal.core:Terminating provider thesubdb
INFO:subliminal.core:Terminating provider tvsubtitles
INFO:subliminal.core:Saving <ShooterSubtitle 'https://www.shooter.cn/api/subapi.php?fetch=MTU5NTk1NTk5NnxsU2xVanJJcFF2YnlKV25ROWlITl9Kc1FkVWk5Vndtck9CejhjZE95SGlVV1JHbVpOVElYeExTR05sMGQxSTI4ZHFvY0JEcktiNzdmaGpBRFZYV0JELVpBSDY4TnpCZzBmaE1mMVIzUktYODNRTzdRQzVvMGVwRUFXelRVYXRBYVpaTDVwOW9QSzlKQURPYmZQRG51a3ZZPXzC_gwXdhO_V83bmLTGLzXutvklLEUje-MdU_K6e6rh0A==&nonce=%0A%B8%18%CA%8D%A3%8CD%60%A9%9E%60x%26%B9V' [en]> to 'The.Good.Place.S03E04.HDTV.x264-SVA.en.srt'
1 subtitle downloaded for The.Good.Place.S03E04.HDTV.x264-SVA.mkv
`

**Comment by Rouzax** [comment]
@ratoaq2 I'm seeing the same issue with Opensubtitle when trying to fetch Dutch subs, it will download CS
```
C:\Scripts>%SubliminalLocation% --debug --opensubtitles USER PASSWORD download -p opensubtitles -l en -l nl "C:\DATA\Movies\Kajillionaire (2020)"
DEBUG:subliminal.cli:Collecting path C:\DATA\Movies\Kajillionaire (2020)
DEBUG:subliminal.core:Walking directory 'C:\\DATA\\Movies\\Kajillionaire (2020)'
INFO:subliminal.core:Scanning video 'Kajillionaire (2020) - [WEBDL-2160p][H265][EAC3 5.1][EN][naisu].mkv' in 'C:\\DATA\\Movies\\Kajillionaire (2020)'
DEBUG:subliminal.core:Size is 11836629461
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with hash
DEBUG:subliminal.refiners.hash:Computing hashes for 'C:\\DATA\\Movies\\Kajillionaire (2020)\\Kajillionaire (2020) - [WEBDL-2160p][H265][EAC3 5.1][EN][naisu].mkv'
DEBUG:subliminal.refiners.hash:Computed hashes {'opensubtitles': 'c4b011ebc8a5211f'}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Found embedded subtitle {<Language [und]>}
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No apikey. Skipping omdb refiner.
1 video collected / 0 video ignored / 0 error
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [en]>, <Language [nl]>}
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'TOKEN,TOKEN'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviehash': 'c4b011ebc8a5211f', 'moviebytesize': '11836629461', 'sublanguageid': 'dut,eng'}, {'tag': 'Kajillionaire (2020) - [WEBDL-2160p][H265][EAC3 5.1][EN][naisu].mkv', 'sublanguageid': 'dut,eng'}, {'query': 'Kajillionaire', 'sublanguageid': 'dut,eng'}]
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1956957445' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1956957444' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '7579' [cs]> by fulltext
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1956957445' [en]> for video <Movie [Kajillionaire (2020)]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 269, 'title': 135, 'year': 45, 'country': 45, 'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'year', 'title', 'source', 'country'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 233 with final matches {'year', 'title', 'hearing_impaired', 'source', 'country'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1956957444' [en]> for video <Movie [Kajillionaire (2020)]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 269, 'title': 135, 'year': 45, 'country': 45, 'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'year', 'title', 'source', 'country'}
INFO:subliminal.score:Computed score 232 with final matches {'year', 'title', 'source', 'country'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '7579' [cs]> for video <Movie [Kajillionaire (2020)]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 269, 'title': 135, 'year': 45, 'country': 45, 'release_group': 15, 'streaming_service': 15, 'source': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'country'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 46 with final matches {'hearing_impaired', 'country'}
INFO:subliminal.core:Downloading subtitle <OpenSubtitlesSubtitle '1956957445' [en]>
INFO:subliminal.providers.opensubtitles:Downloading subtitle <OpenSubtitlesSubtitle '1956957445' [en]>
DEBUG:subliminal.core:Skipping subtitle: <Language [en]> already downloaded
INFO:subliminal.core:Downloading subtitle <OpenSubtitlesSubtitle '7579' [cs]>
INFO:subliminal.providers.opensubtitles:Downloading subtitle <OpenSubtitlesSubtitle '7579' [cs]>
Downloading subtitles  [####################################]  100%  Kajillionaire (2020) - [WEBDL-2160p][H265][EAC3 5.1Downloading subtitles  [####################################]  100%
DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
INFO:subliminal.core:Saving <OpenSubtitlesSubtitle '1956957445' [en]> to 'C:\\DATA\\Movies\\Kajillionaire (2020)\\Kajillionaire (2020) - [WEBDL-2160p][H265][EAC3 5.1][EN][naisu].en.srt'
INFO:subliminal.core:Saving <OpenSubtitlesSubtitle '7579' [cs]> to 'C:\\DATA\\Movies\\Kajillionaire (2020)\\Kajillionaire (2020) - [WEBDL-2160p][H265][EAC3 5.1][EN][naisu].cs.srt'
Downloaded 2 subtitles
```
