### ISSUE TITLE
Use IETF Language representation for subtitle names

### ISSUE THREAD

**Issue by thiagorobis** [Diaoul/subliminal#323]
Hello,
The VLC and XMBC can regonize .PB, as like .POB, to Brazilian Portuguese Subtitle. If possible, can you add to your app?
Thanks

**Comment by Diaoul** [comment]
Need to update `save_subtitles`

**Comment by miigotu** [comment]
@Diaoul also scan_subtitle_languages, scan_videos right? I have users reporting this issue also.

atm we use scan_subtitle_languages to check if we even need to try and get any subs, (and to set languages parameter for download_best_subtitles) then in the download method we scan_videos then download_best_subtitles

quick question too, (getting about 74 scored matches on non hash) in our db we have imdb_id and tvdb_id, but for the show not the episode. In the video object, is it expecting the  tvdb_id/imdb_id of the actual episode or of the show it belongs to?

**Comment by miigotu** [comment]
@Diaoul this seems to be the only special code I get bug reports about. I can't find a way to get subliminal to download pb/pob subs, as it just sets the language.alpha2 to pt if I use language.fromietf('pt-BR') or language.fromopensubtitles('pb') or language.fromopensubtitles('pob').
Regardless of which method it downloads pt subs and saves them as pt. The fromopensubtitles method even sets the alpha3 to `por` instead of 'bra'.

Any chance this is close to getting a solution or is there any way I can work around it for now?
