### ISSUE TITLE
Guessit 2

### ISSUE THREAD

**Issue by Diaoul** [Diaoul/subliminal#550]
Use guessit 2!
@Toilal: I think I'll need your help to replace some part of low level use of guessit 1.x such as [here](https://github.com/Diaoul/subliminal/blob/master/subliminal/subtitle.py#L319-L330)

The use case is simple, I have a string, I know it contains some markers (quality, audio codec, video codec, etc.) but not the full filename and I want to extract them in a guessit-compatible way to reinject them later in the guess object.
How would I do that in guessit 2 ?

**Comment by Bouke** [comment]
Now that Flexget has updated to guessit 2.0, the subliminal plugin in flexget no longer works because of incompatible guessit versions. So to get subliminal plugin working again, flexget must be downgraded to 1.2.430, and installed after subliminal so flexget gets the final saying in which guessit version (being 0.10.3).

**Comment by Toilal** [comment]
I think flexget dependencies have been rolledback, and now subliminal plugin is working fine. But guessit flexget parser plugin is now broken. 

I currently remove depency to regex native module in guessit because it's not acceptable for Flexget nor sickragz, and then i'll release guessit 2.0 final. Then i'll try to open a pull request for subliminal to use guessit 2, should be a matter of a few days, maybe one week or two.

**Comment by Diaoul** [comment]
Thanks @Toilal !
