### ISSUE TITLE
Inconsistent logging levels in some providers (addic7ed and tvsubtitles)

### ISSUE THREAD

**Issue by ratoaq2** [Diaoul/subliminal#619]
There are logging messages with error level where it shouldn't (at least from my perspective). All of them are related to 'no result was found' or 'no match' when searching. This shouldn't be logged as error, it should be at least warning (or even info).

[addic7ed](https://github.com/Diaoul/subliminal/blob/develop/subliminal/providers/addic7ed.py#L226)
[tvsubtitles](https://github.com/Diaoul/subliminal/blob/develop/subliminal/providers/tvsubtitles.py#L111)
[tvsubtitles](https://github.com/Diaoul/subliminal/blob/develop/subliminal/providers/tvsubtitles.py#L163)
[tvsubtitles](https://github.com/Diaoul/subliminal/blob/develop/subliminal/providers/tvsubtitles.py#L169)
##

**Comment by Diaoul** [comment]
I agree logging levels should be consistent (more or less, depending on the provider implementation). Not finding a show or a particular episode is IMO an error for that provider. Not finding subtitles isn't. I use error level when the error need investigation. During normal operations you should always encounter info. If something is odd, warning, if something requires investigation error.

Name matching could be tricky due to special characters and providers usually have all the show/episode information available so an error helps tracking that kind of improper behavior.

I will flag this a documentation issue on how to implement providers.
