### ISSUE TITLE
Support for aliases for release groups to increase matching

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#672]
A similar use case would be aliases for release groups.
Certain subtitles of 1 release group will always be in sync with another release group (example: LOL and DIMENSION)
If aliases could be defined on release group level, it would also improve the matching.
This is certainly useful where subliminal is used in library mode and certain criteria must match before a subtitle is downloaded. If for example a subtitle is available under 'LOL' but the not under 'DIMENSION', it would be nice that 'DIMENSION' is also matched for 'LOL'. 
So making it possible to provide 'aliases' for certain video fields would be a good idea.

**Comment by fernandog** [comment]
Found this but seems a little outdated
https://scenelingo.wordpress.com/2013/07/09/same-people-different-groups/

I still miss a lot like BATV, AVS/BRISK, etc

**Comment by Diaoul** [comment]
Please try latest develop with c9635b3819621f4eef360e791cb8f65ffe9949bf
Additions to the list are welcome as long as they are well-sourced.

I didn't add everything on the list you gave because this is mostly same groups but different categories (like movies vs TV) so you won't find conflicting subtitles as there wont be any conflicting releases.

**Comment by h3llrais3r** [comment]
I think the most important onces are added. :+1: 
Thanks.
