### ISSUE TITLE
Do not discard existing and force continue

### ISSUE THREAD

**Issue by CyberMew** [Diaoul/subliminal#798]
I'm solely using addic7ed for subliminal for my Tv shows. When too many requests error occur, it does two things:
1. Discard any results it has downloaded so far,
2. Skip the rest of the files. 

I think it shouldn't discard the files and should continue to attempt the rest of the files. Sometimes it's just a temporary issue and not being blocked, and need several retries to "fix it". Since this behaviour might not be wanted can we add a flag to force continue?

Also, I mentioned before that when 0 files successfully downloaded, we don't know if it's due to subtitles in the language requested already existed or because no subtitle exists in the search. It would be good if the program report it in greater details instead of 1 or 0. I don't think there exists a situation where it will return "10 subtitle files downloaded for Tv-show.s01e01.mkv" right?

**Comment by Diaoul** [comment]
This is very specific to Addic7ed, instead of cleverly reporting TooManyRequests the server returns an error or times out. There is no way to differentiate this situation or the situation where the server is really down.

Forcing download anyway would mean hammering the server when it's already down, I don't think this is a good idea. Addic7ed provides good quality subtitles but the way to get them is really ugly.

As for your last question, it can happen if you request multiple languages (usually your native language and the original language).

**Comment by CyberMew** [comment]
1 and 2 seems to be solved now.
