### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by abescalamis** [Diaoul/subliminal#908]
I get this error with the Docker version of subliminal

Also, @Diaoul the docker image doesn't have the Unrar tool #853, and the "guess it" fix #800, and because of these 3 issues I only use subliminal for movies and cannot use it for TV shows. These issues are only present in the subliminal docker image (latest and stable), it works well and don't have these issues in the windows and Linux python version of subliminal. 

Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    load_entry_point('subliminal', 'console_scripts', 'subliminal')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/src/app/subliminal/cli.py", line 453, in download
    matches=', '.join(sorted(matches, key=scores.get, reverse=True))
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by mvazquez** [comment]
This also happens to me, with the Linux python version of subliminal, if I increase the verbose level to -vv or more.

**Comment by ratoaq2** [comment]
@mvazquez  Can you provide an example of a failing command line?

**Comment by ratoaq2** [comment]
The latest docker image of subliminal was updated. This shouldn't happen anymore in latest.

Feel free to reopen otherwise

**Comment by ittayd** [comment]
@ratoaq2 , using 2.1.0 installed as a python package, this happens to me

**Comment by varenc** [comment]
I just ran into this bug too.  

It's only a bug when printing out verbose logs. So you can "fix"it just by removing the `-v` or `--verbose` from your subliminal command.  This line in `cli.py` causes it because not all matches have an integer score: https://github.com/Diaoul/subliminal/blob/e25589dbcc5b2455bf9f0b49cf2083bb0eae449f/subliminal/cli.py#L493

My fix is just to replace that line with `matches=matches`, which just means you won't get the nicely sorted list of matches in your verbose log messages. If Diaoul wants I'm happy to submit a proper fix in a PR as well.

Cheers
